#!/bin/bash

secret_number=42
a=0

echo  "Guess the number: "  

while [ $a -ne $secret_number ];
do  read -p "your guess: " a

    if [ $a -eq $secret_number ]; then
       echo "Congrats"
      elif [ $a -gt $secret_number ]; then
       echo "number is high"
      else 
       echo "number is low"
    fi
done
